### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by SiNaPsEr0x** [pielco11/telescan#2]
Traceback (most recent call last):
  File "telescan.py", line 105, in <module>
    with app:
  File "/Users/SiNaPsE/Library/Python/3.7/lib/python/site-packages/pyrogram/client/client.py", line 222, in __enter__
    return self.start()
  File "/Users/SiNaPsE/Library/Python/3.7/lib/python/site-packages/pyrogram/client/client.py", line 825, in start
    is_authorized = self.connect()
  File "/Users/SiNaPsE/Library/Python/3.7/lib/python/site-packages/pyrogram/client/client.py", line 260, in connect
    self.load_config()
  File "/Users/SiNaPsE/Library/Python/3.7/lib/python/site-packages/pyrogram/client/client.py", line 1404, in load_config
    raise AttributeError("No API Key found. More info: https://docs.pyrogram.org/intro/setup")
AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup

but api_id is missing in the code

**Comment by pielco11** [comment]
Updated README and added a template for the creds, should be pretty straightforward right now

**Comment by SiNaPsEr0x** [comment]
Thanks
