### ISSUE TITLE
No API Key found

### ISSUE THREAD

**Issue by AlbanMartin** [pielco11/telescan#4]
Hi ! 

First of all, thanks for the code ! 

I have an issue with Pyrogram. Very strange because Telescan was working very well few days ago. 

Now I have this : 

Traceback (most recent call last):
  File "/Users/XX/telescan/telescan.py", line 90, in <module>
    with app:
  File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 249, in __enter__
    return self.start()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 53, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/auth/connect.py", line 38, in connect
    self.load_config()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 611, in load_config
    raise AttributeError("No API Key found. More info: https://docs.pyrogram.org/intro/setup")
AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup

My API is in api_creds.ini.

I have tried to put in a new doc config.ini but it doesn't work.

**Comment by pielco11** [comment]
Hmm, indeed that's weird.
By looking at how the `.ini` file is being parsed, the issue could reside in the file itself. Still I don't know how it could since the syntax is extremely easy.
Either way, may you try with the second configuration option available as described [here](https://docs.pyrogram.org/intro/setup#configuration)?  You will need to edit a bit of code, but really easy and short steps.

Also, if the issue is really related to pyrogram, I do suggest you to ask them. No worries for me receiving questions and stuff. the point is that they may give you more helpful assistance than me.

**Comment by AlbanMartin** [comment]
I'll try and I let you know !

**Comment by AlbanMartin** [comment]
It's working ! Thanks !
