### ISSUE TITLE
TypeError: Client.__init__() got an unexpected keyword argument 'config_file'

### ISSUE THREAD

**Issue by CoffeeNData** [pielco11/telescan#6]
It simply wont run.
Command: `python3 telescan.py api_creds.ini`
```
Traceback (most recent call last):
  File "/home/user/telescan/telescan.py", line 10, in <module>
    app = Client(
TypeError: Client.__init__() got an unexpected keyword argument 'config_file'
```

**Comment by rangersmyth74** [comment]
I am getting this error also. 

└─$ python telescan.py api_creds.ini
Traceback (most recent call last):
  File "/home/kali/apps/telescan/telescan.py", line 9, in <module>
    app = Client(
TypeError: Client.__init__() got an unexpected keyword argument 'config_file'

I tried python and python3 and the same error. 
I also had to install pip install TgCrypto, but I got the same error!

**Comment by osinter456** [comment]
you know where is config_file ?

**Comment by bpavuk** [comment]
Same. Maybe, we should try to use an old pyrogram

**Comment by vtombez** [comment]
still no solution?

**Comment by pielco11** [comment]
The latest version released at the time of the last commit is:
- https://github.com/pyrogram/pyrogram/releases/tag/v1.0.0

The next one, v1.1.0, was released in 12/2020. Backwards compatibility is not for granted

> But now Pyrogram is v2.0.102

Yes

**Comment by passthesh3ll** [comment]
I installed **pyogram==1.1.0** but there is another problem
@pielco11 could you post the original dependences and python version please? 

```
(.venv) ➜  telescan git:(master) ✗ python3 telescan.py api_creds.ini
Traceback (most recent call last):
  File "/home/redacted/redacted/telescan/telescan.py", line 4, in <module>
    from pyrogram import Client
  File "/home/redacted/redacted/telescan/.venv/lib/python3.13/site-packages/pyrogram/__init__.py", line 40, in <module>
    from . import raw, types, filters, handlers, emoji
  File "/home/redacted/redacted/telescan/.venv/lib/python3.13/site-packages/pyrogram/types/__init__.py", line 22, in <module>
    from .input_media import *
  File "/home/redacted/redacted/telescan/.venv/lib/python3.13/site-packages/pyrogram/types/input_media/__init__.py", line 19, in <module>
    from .input_media import InputMedia
  File "/home/redacted/redacted/telescan/.venv/lib/python3.13/site-packages/pyrogram/types/input_media/input_media.py", line 21, in <module>
    from ..messages_and_media import MessageEntity
  File "/home/redacted/redacted/telescan/.venv/lib/python3.13/site-packages/pyrogram/types/messages_and_media/__init__.py", line 31, in <module>
    from .sticker import Sticker
  File "/home/redacted/redacted/telescan/.venv/lib/python3.13/site-packages/pyrogram/types/messages_and_media/sticker.py", line 21, in <module>
    from async_lru import alru_cache
  File "/home/redacted/redacted/telescan/.venv/lib/python3.13/site-packages/async_lru.py", line 95, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

**Comment by pielco11** [comment]
Hi @evilsh3ll , sincerely I'm quite overwhelmed in this period so here is a quick answer: I don't recall which version I was running at that time, but I guess it was the latest. Yes, I agree, I should have specified the right version in the requirements file. My bad

In the mean time one may look at which release was available that time and come back to us with an answer. I'm happy to accept any working PR

I'm not sure when I find some capacity for this
